CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_TRIMESTRE_DATAMART`(
	IN VAR_ID INT,
    IN VAR_F_INICIO DATE,
    IN VAR_F_FIN DATE,
    IN VAR_TRIMESTRE VARCHAR(25))
BEGIN
	INSERT INTO db_cyad_posgrado_datamart.cat_trimestres
	(`ID`,
	`FECHA_FIN`,
	`FECHA_INICIO`,
	`TRIMESTRE`,
    `ISPROCESADO`)
	VALUES
	(VAR_ID,
	VAR_F_INICIO,
    VAR_F_FIN,
    VAR_TRIMESTRE,
    FALSE);
END